### ISSUE TITLE
Getting Windows Defender alert

### ISSUE THREAD

**Issue by fguendling** [magicmark/pre-commit-vscode#194]
Can anyone explain? On Windows 11. Else, I might report/ escalate this later

**Comment by fguendling** [comment]
Related to the domain fluffy.cc

**Comment by magicmark** [comment]
cc @chriskuehl

**Comment by chriskuehl** [comment]
Already responded in your issue [#175](https://github.com/chriskuehl/fluffy/issues/175) but I'll paste it here:

> There are some details in https://github.com/chriskuehl/fluffy/issues/79. Basically, the upload policy used to be very open (it was only used by me and my friends) and someone started distributing malware through it. As a result the domain was put on various security vendors's blocklists.
>
> I spent a bunch of time adding upload restrictions, virus scanning, and other features to try to prevent malware which has more or less worked, but it seems impossible to get off these lists permanently. I've submitted a bunch of removal requests to various companies to request the domain be unblocked. Most of the requests are successful, but then a few months later it's blocked again for reasons unknown to me. I gave up and usually don't bother anymore now that the main usage of fluffy is internally at companies.
>
> As far as I know there is no malware hosted now but there's not much I can do about the blocking.

Maybe better to use a larger host which security companies care enough about to not block. I've given up trying to chase these down because they just re-block the domain later on for no apparent reason.
